title: "The Kendrick Brothers"
baseurl: https://markindra.github.io/TestSite/
collections:
  films:
    output: true
    sort_by: year
  books:
    output: true
    sort_by: family
  members:
    output: true
  studies:
    output: true
    sort_by: family
  articles:
    output: true
