name : Google Forms Post

# Run whenever webhook dispatch with name 'new_post' is received
on:
  repository_dispatch:
    types:
      - new_post

# Only one job to do
jobs:
  commit:
    name: Commit new post
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Write webhook payload to file
    - name: Write files
      run: |
        cat > "${{ github.event.client_payload.filename }}" << EOL ${{ github.event.client_payload.content }}
        EOL
    # Use pull request action to commit changes to PR branch
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: New Post Added (${{ github.event.client_payload.postname }})
        commit-message: Add post - ${{ github.event.client_payload.postname }}
        author: ${{ github.event.client_payload.author }} <actions@github.com>
        branch: new-posts/${{ github.event.client_payload.postname }}
        labels: posts
        body: |
          New post by ${{ github.event.client_payload.author }} added using Google Forms. Approve below
            - Added file ${{ github.event.client_payload.filename }}
            - Auto-generated by Apps Script and Actions workflow
